name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Check out the repository code
    - name: Checkout repository
      uses: actions/checkout@v3
    
    # Step 2: Cache Python dependencies for faster builds
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    # Step 3: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    # Step 4: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    # Step 5: Lint the code using flake8
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 src/ tests/ --count --select=E9,F63,F7,F82 --show-source --statistics
    
    # Step 6: Run tests using pytest
    - name: Test with pytest
      run: |
        pip install pytest pytest-cov
        pytest --cov=src tests/

  docker:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    # Step 1: Check out the repository code
    - name: Checkout repository
      uses: actions/checkout@v3
    
    # Step 2: Set up Docker Buildx for cross-platform builds
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    # Step 3: Log in to Docker Hub (Add secrets for credentials)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    # Step 4: Build and push the Docker images
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/automated-trading-agent:latest
